raw:
  base_path: "src/files/raw"
  folders:
    - name: "games"
      required_columns:
        - "gameID"
        - "date"
        - "homeTeamID"
        - "awayTeamID"
        - "homeGoals"
        - "awayGoals"
    - name: "players_appearances"
      required_columns:
        - "gameID"
        - "playerID"
        - "time"
    -  name: "teamstats"
       required_columns:
         - "gameID"
         - "teamID"
         - "date"
         - "result"
    -  name: "heatmaps"
       required_columns:
         - "zones"
