folders:
  - name: "games"
    files:
      - name: "games.csv"
        columns:
          "gameID": "int"
          "date": "date"
          "homeTeamID": "int"
          "awayTeamID": "int"
          "homeGoals": "int"
          "awayGoals": "int"
  - name: "players_appearances"
    files:
      - name: "appearances.csv"
        columns:
          "gameID": "int"
          "playerID": "int"
          "time": "int"
  - name: "teamstats"
    files:
      - name: "teamstats.csv"
        columns:
          "gameID": "int"
          "teamID": "int"
          "date": "date"
          "result": "str"


